function correlation = findCorrelation(Data,Cm)

% A simple function that takes in two properties
    % Data: The experimental data
    % Cm: The theoretical data generated by equations.

    % The correlation matrix is generated by a MATLAB Function
    CorrMatrix = corrcoef(Data,Cm);

    % Here only the relevant value is extracted is retrieved from the
    % matrix
    correlation = CorrMatrix(2,1);
end 